apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: elasticsearch-deployment
  namespace: common
  labels:
    app: elasticsearch-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch-db
  template:
    metadata:
      labels:
        app: elasticsearch-db
    spec:
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:7.1.0
        imagePullPolicy: IfNotPresent
        env:
        - name: discovery.type
          value: "single-node"
        resources:
          limits:
            memory: "6Gi"
            cpu: "1000m"
          requests:
            memory: "4Gi"
            cpu: "500m"
        ports:
        - containerPort: 9200
        - containerPort: 9300
        volumeMounts:
        - mountPath: "/usr/share/elasticsearch/data"
          name: elasticsearch-storage
        # - mountPath: "/usr/share/elasticsearch/config"
        #   name: elasticsearch-configmap
      volumes:
      - name: elasticsearch-storage
        persistentVolumeClaim:
          claimName: elastic-storage-claim
      # - name: elasticsearch-yml
      #     configMap:
      #       name: elasticsearch-configmap