kind: PersistentVolume
apiVersion: v1
metadata:
  name: mysql-storage
  namespace: db
  labels:
    type: local
    app_name: mysql
spec:
  storageClassName: local-storage
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/kube-vol/mysql"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-storage-claim
  namespace: db
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 20Gi
  storageClassName: local-storage
  selector:
    matchLabels:
      app_name: "mysql"