apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: db
  labels:
    app: mysql-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-db
  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      containers:
      - name: mysql
        image: tasktrack.telekom.at/remote-docker/mariadb:10.3
        imagePullPolicy: IfNotPresent
        env:
        - name: MYSQL_DATABASE
          value: keycloak
        - name: MYSQL_USER
          value: keycloak
        - name: MYSQL_PASSWORD
          value: keycloak
        - name: MYSQL_ROOT_PASSWORD
          value: mysql
        ports:
        - containerPort: 3306
          name: mysql
        resources:
          limits:
            memory: "4Gi"
            cpu: "1000m"
          requests:
            memory: "2Gi"
            cpu: "500m"
        volumeMounts:
        - mountPath: "/var/lib/mysql"
          name: mysql-storage
      imagePullSecrets:
      - name: tasktrack.telekom.at
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-storage-claim
