module.exports = {
  EN: {
    'no discount': 'no discount',
    '50% discount': '50% discount',
    '100% discount': '100% discount',
    'Transaction Fee': '',
    'Product Move': 'Product Move',
    'Change Ownership': 'Change Ownership',
    'HFHS Cockpit': 'HFHS Cockpit',
    Welcome: 'Welcome',
    Name: 'Name',
    SidID: 'SidID',
    'Names and SidIds': 'Names and SidIds',
  },
  DE: {
    'no discount': 'Kein Rabatt',
    '50% discount': '50% Rabatt',
    '100% discount': '100% Rabatt',
    'Transaction Fee': '',
    'Product Move': 'Produktverschub',
    'Change Ownership': 'Übertragung',
    'HFHS Cockpit': 'Kundenübergreifende Prozesse',
    Welcome: 'Willkommen',
    Name: 'Name',
    SidID: 'SidID',
    'Names and SidIds': 'Namen und SidIds',
  },
};
