module.exports = {
  EN: {
    'no discount': 'no discount',
    '50% discount': '50% discount',
    '100% discount': '100% discount',
    'Transaction Fee': '',
    'Product Move': 'Product Move',
    'Change Ownership': 'Change Ownership',
    'HFHS Cockpit': 'HFHS Cockpit',
    Welcome: 'Welcome',
    Name: 'Name',
    SidID: 'SidID',
    'Name And SidID': 'Name And SidID',
  },
    'New customer': 'New customer',
    'Previous customer': 'Previous customer',
    'New and Previous customer':'New and Previous customer',
    'Suppress customer letters':'Suppress customer letters',

      },
  DE: {
    'no discount': 'Kein Rabatt',
    '50% discount': '50% Rabatt',
    '100% discount': '100% Rabatt',
    'Transaction Fee': '',
    'Product Move': 'Produktverschub',
    'Change Ownership': 'Übertragung',
    'HFHS Cockpit': 'Kundenübergreifende Prozesse',
    Welcome: 'Willkommen',
    Name: 'Name',
    SidID: 'SidID',
    'Name And SidID': 'Name And SidID',
  },
};
