apiVersion: apps/v1
kind: Deployment
metadata:
  name: microfrontend-product-move
  namespace: $NAMESPACE
  labels:
    app: microfrontend-product-move
    A1.project: HSHF
spec:
  replicas: $REPLICA_COUNT
  selector:
    matchLabels:
      app: microfrontend-product-move
  template:
    metadata:
      labels:
        app: microfrontend-product-move
    spec:
      containers:
      - name: microfrontend-product-move
        image: tasktrack.telekom.at/gucci-docker/microfrontend-product-move:$IMAGE_VERSION
        imagePullPolicy: Always
        env:
        - name: NODE_ENV
          value: $NODE_ENV
        - name: ESB_USER
          valueFrom:
            secretKeyRef:
              name: ccf-esb-user
              key: user
        - name: ESB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ccf-esb-user
              key: password
        - name: PARTY_MASTER_AUTH_SYSTEM
          valueFrom:
            secretKeyRef:
              name: ccf-esb-user
              key: partyMasterAuthSystem
        - name: PARTY_MASTER_AUTH_USER
          valueFrom:
            secretKeyRef:
              name: ccf-esb-user
              key: partyMasterAuthUser
        - name: HFHS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: hfhs-db
              key: HFHS_DB_PASSWORD
        - name: HFHS_DB_URL
          valueFrom:
            secretKeyRef:
              name: hfhs-db
              key: HFHS_DB_URL
        - name: HFHS_DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: hfhs-db
              key: HFHS_DB_USERNAME
        - name: WIDGET_NAME
          value: "product-move"
        - name: LOG_FOLDER
          value: "/opt/app/src/logs/*.log"
        ports:
        - containerPort: 6102
        envFrom:
        - configMapRef:
            name: gucci-config
      imagePullSecrets:
      - name: tasktrack.telekom.at